mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls')),
    path('storage/', include('my_storage.urls')),
]

handler404="main.views.error404"
handler500="main.views.error500"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', main_page, name='home'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin-page'),
    path('', include('news.urls'), name= 'home'),
    path('storage/', include('my_storage.urls')),
    path('user/', include('user.urls'))
]

handler404="news.views.error404"

if settings.DEBUG:
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls')),] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('register/', register, name = 'register'),
    path('login/', user_login, name = 'login'),
    path('logout/', user_logout, name = 'logout'),
    path('profile/', user_profile, name = 'profile'),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

from django.conf import settings

class CustomUser(AbstractUser):
    acess_level = models.IntegerField(
        default=1,
        verbose_name="Уровень Доступа",
        choices=settings.ACESS_LEVELS,
        blank=False,
        validators=[
            MaxValueValidator(4),
            MinValueValidator(1)
        ]
        )
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)

    def __str__(self):
        return self.username

mysite/user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username= forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    email = forms.EmailField(
        label='Почта',
        widget=forms.EmailInput(attrs={'class': 'form-control'}))


    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class UserLoginForm(AuthenticationForm):
    username= forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    email = forms.EmailField(
        label='Почта',
        widget=forms.EmailInput(attrs={'class': 'form-control'}))


    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

mysite/user/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout

from .forms import UserRegisterForm, UserLoginForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы были успешно зарегистрированны')
            return redirect('home', permanent=True)
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home', permanent=True)
    else:
        form = UserLoginForm()

    return render(request, 'user/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login', permanent=True)

mysite/users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout


from .forms import UserRegisterForm, UserLoginForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Вы были успешно зарегистрированны')
            return redirect('home', permanent=True)
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home', permanent=True)
    else:
        form = UserLoginForm()

    return render(request, 'users/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login', permanent=True)


def user_profile(request):
    return render(request, 'users/profile.html', {'user': request.user})

mysite/users/templates/users/login.html
{% extends 'base_user.html' %}
{% load static %}

{% block title %}
{{ block.super }}: Авторизация
{% endblock %}

{% block body %}
{% block alert %}
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'error' %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% else %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endif %}

{% endfor %}
{% endif %}
{% endblock %}
<div class = "form">
    <h1>Авторизация</h1>
    <div class = "form__item">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="form__button">Авторизоваться</a>
        </form>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'base_user.html' %}


{% block title %}
{{ block.super }} : {{ request.user }}
{% endblock %}

{% block body %}
<div class = "profile-card">
    <h1>Профиль пользователя: {{request.user.username | upper}}</h1>
    <div class = "profile-content">
        <div id = "leftside">
        <p>Фото:</p>
        {% if request.user.photo %}
        <img src ="{{request.user.photo.url}}" alt = "">
        {% endif %}
        </div>
        <div id = "rightside">
            {% block rightside %}
            <p>Ник: <b>{{request.user.username}}</b></p>
            <p>Почта: {{request.user.email}}</p>
            <p>Уровень доступа: <b>{{request.user.get_acess_level_display}}</b></p>
            <p>Дата регистрации: {{request.user.date_joined|date:"j F Y H:i" }}</p>
            <p>Последний вход: В {{request.user.last_login|date:"H:i j F Y"}}</p>
            {% if request.user.is_superuser%}
                <a href ="{% url 'admin:index' %}">Админ-Панель</a>
            {% endif%}
            {% endblock%}
        </div>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/register.html
{% extends 'base_user.html' %}
{% load static %}

{% block title %}
{{ block.super }}: Регистрация
{% endblock %}

{% block body %}

{% block alert %}
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    <p>{{ message }}</p>
                </div>
            {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <p>{{ message }}</p>
                </div>
            {% endif %}

        {% endfor %}
        {% endif %}
{% endblock %}
    <div class = "form">
            <h1>Регистрация</h1>
        <div class = "form__item">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="form__button">Зарегестрироваться</a>
            </form>
        </div>
    </div>
{% endblock %}